MSGT(	MSG_TYPE_RESERVED)		//	
MSGT(	SCAN_INFO)			//
MSGT(	SCAN_UPDATE_REQ)
MSGT(	SCAN_UPDATE)
MSGT(	INTERLOCK)
MSGT(	LINK_ERROR)
MSGT(	MEASURE_DEPTH)			//	
MSGT(	LENGTH_OPT)
MSGT(	HEARTBEAT)
MSGT(	HANDOVER)
MSGT(	LINK_INFO)
MSGT(	LEADER)
